version: '3.9'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "8000:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  web1:
    container_name: apache_php1
    build: ./docker/web
    environment:
      - VIRTUAL_HOST=localhost
    volumes:
      - ./public_html:/var/www/html
      - ./docker/logs:/var/log/httpd
    depends_on:
      - master
      - slave
  web2:
    container_name: apache_php2
    build: ./docker/web
    environment:
      - VIRTUAL_HOST=localhost
    volumes:
      - ./docker/logs:/var/log/httpd
    depends_on:
      - master
      - slave

  master:
    container_name: mysql_master
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - ./db/master/:/conf
      - ./setup.sh:/usr/local/bin/setup.sh
      - master_log:/var/log/mysql/
      - master_db:/var/lib/mysql
    tty: true
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'master'
    command: >
      bash -c "
      cp db/master/my.cnf /etc/mysql/conf.d/ &&
      chmod 644 /etc/mysql/conf.d/my.cnf &&
      /entrypoint.sh mysqld"
    networks:
      - redundancy-network

  slave:
    container_name: mysql_slave
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - ./db/slave/:/conf
      - ./setup.sh:/usr/local/bin/setup.sh
      - slave_log:/var/log/mysql/
      - slave_db:/var/lib/mysql
    tty: true
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'slave'
    command: >
      bash -c "
      cp /db/slave/my.cnf /etc/mysql/conf.d/ &&
      chmod 644 /etc/mysql/conf.d/my.cnf &&
      /entrypoint.sh mysqld"
    networks:
      - redundancy-network

  phpmyadmin1:
    container_name: phpmyadmin1
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=master
      - PMA_USER=user
      - PMA_PASSWORD=password
    links:
      - master
    volumes:
      - /sessions
      - ./docker/web/php.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
  phpmyadmin2:
    container_name: phpmyadmin2
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=slave
      - PMA_USER=user
      - PMA_PASSWORD=password
    links:
      - slave
    volumes:
      - /sessions
      - ./docker/web/php.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini

volumes:
  master_db: {}
  master_log: {}
  slave_db: {}
  slave_log: {}

networks:
  redundancy-network:
    driver: bridge